"""scope activities objectifs plans and rapports by user

Revision ID: 080d4ba23719
Revises: a6e289d12842
Create Date: 2026-07-26 19:54:25.412577

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "080d4ba23719"
down_revision: str | Sequence[str] | None = "a6e289d12842"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("activities", sa.Column("user_id", sa.Integer(), nullable=False))
    op.drop_constraint("uq_activities_garmin_activity_id", "activities", type_="unique")
    op.create_index(op.f("ix_activities_user_id"), "activities", ["user_id"], unique=False)
    op.create_unique_constraint(
        "uq_activities_user_id_garmin_activity_id",
        "activities",
        ["user_id", "garmin_activity_id"],
    )
    op.create_foreign_key("fk_activities_user_id_users", "activities", "users", ["user_id"], ["id"])
    op.add_column("objectifs", sa.Column("user_id", sa.Integer(), nullable=False))
    op.create_index(op.f("ix_objectifs_user_id"), "objectifs", ["user_id"], unique=False)
    op.create_foreign_key("fk_objectifs_user_id_users", "objectifs", "users", ["user_id"], ["id"])
    op.add_column("plans", sa.Column("user_id", sa.Integer(), nullable=False))
    op.create_index(op.f("ix_plans_user_id"), "plans", ["user_id"], unique=False)
    op.create_foreign_key("fk_plans_user_id_users", "plans", "users", ["user_id"], ["id"])
    op.add_column("rapports", sa.Column("user_id", sa.Integer(), nullable=False))
    op.drop_constraint("uq_rapports_garmin_activity_id", "rapports", type_="unique")
    op.create_index(op.f("ix_rapports_user_id"), "rapports", ["user_id"], unique=False)
    op.create_unique_constraint(
        "uq_rapports_user_id_garmin_activity_id", "rapports", ["user_id", "garmin_activity_id"]
    )
    op.create_foreign_key("fk_rapports_user_id_users", "rapports", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_rapports_user_id_users", "rapports", type_="foreignkey")
    op.drop_constraint("uq_rapports_user_id_garmin_activity_id", "rapports", type_="unique")
    op.drop_index(op.f("ix_rapports_user_id"), table_name="rapports")
    op.create_unique_constraint(
        "uq_rapports_garmin_activity_id", "rapports", ["garmin_activity_id"]
    )
    op.drop_column("rapports", "user_id")
    op.drop_constraint("fk_plans_user_id_users", "plans", type_="foreignkey")
    op.drop_index(op.f("ix_plans_user_id"), table_name="plans")
    op.drop_column("plans", "user_id")
    op.drop_constraint("fk_objectifs_user_id_users", "objectifs", type_="foreignkey")
    op.drop_index(op.f("ix_objectifs_user_id"), table_name="objectifs")
    op.drop_column("objectifs", "user_id")
    op.drop_constraint("fk_activities_user_id_users", "activities", type_="foreignkey")
    op.drop_constraint("uq_activities_user_id_garmin_activity_id", "activities", type_="unique")
    op.drop_index(op.f("ix_activities_user_id"), table_name="activities")
    op.create_unique_constraint(
        "uq_activities_garmin_activity_id", "activities", ["garmin_activity_id"]
    )
    op.drop_column("activities", "user_id")
    # ### end Alembic commands ###
