"""add garmin credentials to users

Revision ID: 76a64fa5d4e9
Revises: 9bf7962b7c33
Create Date: 2026-07-26 21:17:16.518718

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "76a64fa5d4e9"
down_revision: str | Sequence[str] | None = "9bf7962b7c33"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("garmin_email", sa.String(), nullable=True))
    op.add_column("users", sa.Column("garmin_password_encrypted", sa.String(), nullable=True))
    op.add_column("users", sa.Column("garmin_session_encrypted", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "garmin_session_encrypted")
    op.drop_column("users", "garmin_password_encrypted")
    op.drop_column("users", "garmin_email")
    # ### end Alembic commands ###
