"""add gemini api key to users

Revision ID: 9bf7962b7c33
Revises: 080d4ba23719
Create Date: 2026-07-26 20:20:00.307003

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9bf7962b7c33"
down_revision: str | Sequence[str] | None = "080d4ba23719"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("gemini_api_key_encrypted", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "gemini_api_key_encrypted")
    # ### end Alembic commands ###
