"""create activities table

Revision ID: af825642ab7e
Revises: 
Create Date: 2026-07-24 11:25:39.797833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af825642ab7e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('garmin_activity_id', sa.String(), nullable=False),
    sa.Column('sport', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('distance_meters', sa.Float(), nullable=True),
    sa.Column('average_heart_rate', sa.Float(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('garmin_activity_id', name='uq_activities_garmin_activity_id')
    )
    op.create_index(op.f('ix_activities_garmin_activity_id'), 'activities', ['garmin_activity_id'], unique=False)
    op.create_index(op.f('ix_activities_started_at'), 'activities', ['started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activities_started_at'), table_name='activities')
    op.drop_index(op.f('ix_activities_garmin_activity_id'), table_name='activities')
    op.drop_table('activities')
    # ### end Alembic commands ###
