"""create rapports table

Revision ID: f24ae4a9a0c1
Revises: af825642ab7e
Create Date: 2026-07-24 14:35:40.650666

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f24ae4a9a0c1"
down_revision: str | Sequence[str] | None = "af825642ab7e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rapports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("garmin_activity_id", sa.String(), nullable=False),
        sa.Column("strengths", sa.String(), nullable=False),
        sa.Column("improvements", sa.String(), nullable=False),
        sa.Column("generated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("garmin_activity_id", name="uq_rapports_garmin_activity_id"),
    )
    op.create_index(
        op.f("ix_rapports_garmin_activity_id"), "rapports", ["garmin_activity_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_rapports_garmin_activity_id"), table_name="rapports")
    op.drop_table("rapports")
    # ### end Alembic commands ###
